version: '3'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.1.4
    container_name: keycloak
    tty: true
    stdin_open: true
    ports:
      - "8080:8080" 
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin # 管理ユーザーIDを設定
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin # 管理ユーザーのパスワードを設定
    command:
      - start-dev # 開発モードで起動